// marketsReducer
export const GET_FOREX_HEAT_MAP_CURRENCIES = 'GET_FOREX_HEAT_MAP_CURRENCIES';

// screenOptionReducer
export const SET_SCREEN_OPTION_RENDER = 'SET_SCREEN_OPTION_RENDER';
export const GET_SCREEN_OPTION_RENDER = 'GET_SCREEN_OPTION_RENDER';

// currenciesReducer
export const GET_CURRENCIES_DATA = 'GET_CURRENCIES_DATA';